service: komiks-api

frameworkVersion: ">=1.0.0 <2.0.0"

custom:
  stage: ${opt:stage, 'local'}

provider:
  name: aws
  runtime: java8
  environment: ${file(env.yml):${self:custom.stage}}
  region: ${file(env.yml):${self:custom.stage}.REGION}
  versionFunctions: false

package:
  individually: true

functions:
  template:
    handler: com.komiks.api.LambdaEntryPoint::handleRequest
    timeout: 30
    package:
      artifact: template/build/distributions/template.zip
    events:
      - http:
          path: /template/{proxy+}
          method: any
  inventory:
    handler: com.komiks.api.LambdaEntryPoint::handleRequest
    timeout: 30
    package:
      artifact: inventory/build/distributions/inventory.zip
    events:
      - http:
          path: /inventory/{proxy+}
          method: any
  users:
    handler: com.komiks.api.LambdaEntryPoint::handleRequest
    timeout: 30
    package:
      artifact: users/build/distributions/users.zip
    events:
      - http:
          path: /users/{proxy+}
          method: any
