name: CI

on: [push]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Copy ENV file
      run: echo "${ENV_YML}" > env.yml
      env:
        ENV_YML: ${{ secrets.ENV_YML }}
    - run: cat env.yml | wc -l
    - run: cat env.yml
    - run: ls -lh .
    - run: cat build.gradle

