name: CI
on: push
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: study branch only
        uses: actions/bin/filter@b2bea07
        with:
          args: branch feature/npm-study

      - name: npm install
        uses: actions/npm@master
        with:
          args: install

      - name: serverless deploy
        uses: serverless/github-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: deploy
