name: CI

on: [push]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: GitHub Action for npm
      uses: actions/npm@1.0.0
      with:
        args: install

    - name: List Files
      run: ls -lh *

    - name: Serverless deployment
      uses: serverless/github-action@v1.49.0
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
